return {
	"nvim-treesitter/nvim-treesitter-textobjects",
	lazy = true,
	config = function()
		---@diagnostic disable-next-line: missing-fields
		require("nvim-treesitter.configs").setup({
			textobjects = {
				select = {
					enable = true,
					lookahead = true,
				},
				swap = {
					enable = true,
				},
				move = {
					enable = true,
					set_jumps = true,
				},
			},
		})

		local ts_select = require("nvim-treesitter-textobjects.select")
		local ts_swap = require("nvim-treesitter-textobjects.swap")
		local ts_move = require("nvim-treesitter-textobjects.move")

		vim.keymap.set({ "o", "x" }, "la", function()
			ts_select.select_textobject("@assignment.lhs", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "ra", function()
			ts_select.select_textobject("@assignment.rhs", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "aa", function()
			ts_select.select_textobject("@parameter.outer", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "ia", function()
			ts_select.select_textobject("@parameter.inner", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "ai", function()
			ts_select.select_textobject("@conditional.outer", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "ii", function()
			ts_select.select_textobject("@conditional.inner", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "al", function()
			ts_select.select_textobject("@loop.outer", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "il", function()
			ts_select.select_textobject("@loop.inner", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "af", function()
			ts_select.select_textobject("@call.outer", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "if", function()
			ts_select.select_textobject("@call.inner", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "am", function()
			ts_select.select_textobject("@function.outer", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "im", function()
			ts_select.select_textobject("@function.inner", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "ac", function()
			ts_select.select_textobject("@class.outer", "textobjects")
		end)
		vim.keymap.set({ "o", "x" }, "ic", function()
			ts_select.select_textobject("@class.inner", "textobjects")
		end)

		vim.keymap.set("n", "<leader>na", function()
			ts_swap.swap_next("@parameter.inner")
		end)
		vim.keymap.set("n", "<leader>nm", function()
			ts_swap.swap_next("@function.outer")
		end)
		vim.keymap.set("n", "<leader>pa", function()
			ts_swap.swap_previous("@parameter.inner")
		end)
		vim.keymap.set("n", "<leader>pm", function()
			ts_swap.swap_previous("@function.outer")
		end)

		vim.keymap.set("n", "mf", function()
			ts_move.goto_next_start("@call.outer")
		end)
		vim.keymap.set("n", "mm", function()
			ts_move.goto_next_start("@function.outer")
		end)
		vim.keymap.set("n", "mc", function()
			ts_move.goto_next_start("@class.outer")
		end)
		vim.keymap.set("n", "mi", function()
			ts_move.goto_next_start("@conditional.outer")
		end)
		vim.keymap.set("n", "ml", function()
			ts_move.goto_next_start("@loop.outer")
		end)
		vim.keymap.set("n", "mF", function()
			ts_move.goto_next_end("@call.outer")
		end)
		vim.keymap.set("n", "mM", function()
			ts_move.goto_next_end("@function.outer")
		end)
		vim.keymap.set("n", "mC", function()
			ts_move.goto_next_end("@class.outer")
		end)
		vim.keymap.set("n", "mI", function()
			ts_move.goto_next_end("@conditional.outer")
		end)
		vim.keymap.set("n", "mL", function()
			ts_move.goto_next_end("@loop.outer")
		end)
		vim.keymap.set("n", "Mf", function()
			ts_move.goto_previous_start("@call.outer")
		end)
		vim.keymap.set("n", "Mm", function()
			ts_move.goto_previous_start("@function.outer")
		end)
		vim.keymap.set("n", "Mc", function()
			ts_move.goto_previous_start("@class.outer")
		end)
		vim.keymap.set("n", "Mi", function()
			ts_move.goto_previous_start("@conditional.outer")
		end)
		vim.keymap.set("n", "[l", function()
			ts_move.goto_previous_start("@loop.outer")
		end)
		vim.keymap.set("n", "MF", function()
			ts_move.goto_previous_end("@call.outer")
		end)
		vim.keymap.set("n", "MM", function()
			ts_move.goto_previous_end("@function.outer")
		end)
		vim.keymap.set("n", "MC", function()
			ts_move.goto_previous_end("@class.outer")
		end)
		vim.keymap.set("n", "MI", function()
			ts_move.goto_previous_end("@conditional.outer")
		end)
		vim.keymap.set("n", "ML", function()
			ts_move.goto_previous_end("@loop.outer")
		end)

		local ts_repeat_move = require("nvim-treesitter-textobjects.repeatable_move")

		vim.keymap.set({ "n", "x", "o" }, ";", ts_repeat_move.repeat_last_move_next)
		vim.keymap.set({ "n", "x", "o" }, ",", ts_repeat_move.repeat_last_move_previous)

		vim.keymap.set({ "n", "x", "o" }, "f", ts_repeat_move.builtin_f_expr, { expr = true })
		vim.keymap.set({ "n", "x", "o" }, "F", ts_repeat_move.builtin_F_expr, { expr = true })
		vim.keymap.set({ "n", "x", "o" }, "t", ts_repeat_move.builtin_t_expr, { expr = true })
		vim.keymap.set({ "n", "x", "o" }, "T", ts_repeat_move.builtin_T_expr, { expr = true })
	end,
}
