# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml

[hyprland]
background_path = "/home/ArchGamer/Bilder/wallpapers/cat_pacman.png"
bar = "waybar"
browser = "firefox"
color_scheme = "prefer-dark"
editor = "nvim"
explorer = "Yazi"
font = "MesloLGL Nerd Font Mono"
font_size = 12
monospace_font = "MesloLGL Nerd Font Mono"
monospace_font_size = 12

[notification]
font = "MesloLGL Nerd Font Mono"
font_size = 12

[rofi]
scale = 12

[wallpaper]
custom_paths = ["/home/ArchGamer/Bilder/wallpapers"]
